package org.jetbrains.youtrack.bot

val noSubsystemManager = "@yole"

val subsystemsManagers = mapOf(
        "Front-end" to "@stanislav.erokhin",
        "Front-end. Declarations" to "@dmitry.petrov",
        "Front-end. Resolution and Inference" to "@stanislav.erokhin",
        "Front-end. Control-flow analysis" to "@dmitry.savvinov",
        "Front-end. Lexer & Parser" to "@denis.zharkov",

        "Java Descriptors and Signatures" to "@denis.zharkov",
        "Back-end. JVM" to "@dmitry.petrov",
        "Back-end. JavaScript" to "@bashor",
        "Language design" to "@denis.zharkov",
        "Reflection" to "@udalov",
        "Binary Metadata" to "@udalov",
        "Libraries" to "@ilya.gorbunov",
        "Android" to "@yan",

        "Tools" to "@alexey.tsvetkov",
        "Tools. Ant" to "@udalov",
        "Tools. Maven" to "@sergey.mashkov",
        "Tools. CLI" to "@udalov",
        "Tools. kapt" to "@yan",
        "Tools. REPL" to "@yan",
        "Tools. Dokka" to "@semoro",
        "Tools. Gradle" to "@sergey.igushkin",
        "Tools. J2K" to "@semoro",
        "Docs" to "@sergey.igushkin",
        "Tools. JPS" to "@alexey.tsvetkov",
        "Tools. Incremental Compile" to "@alexey.tsvetkov",
        
        "IDE" to "@alefas",
        "IDE. Completion" to "@semoro",
        "IDE. Edu" to "@nastelaz",
        "IDE. Refactorings" to "@alexey.sedunov",
        "IDE. Inspections and Intentions" to "@mikhailglukhikh",
        "IDE. Debugger" to "@yan",
        "IDE. CLion" to "@vyacheslav.karpukhin",

        "Eclipse Plugin" to "@mikhail.zarechenskiy",
        "Web Demo" to "@romanbelov",
        "Web Site" to "@romanbelov",
        "Infrastructure" to "@vyacheslav.gerasimov",
        "IR" to "@dmitry.petrov",
        "Native" to "@nikolay.igotti",
        "[No subsystem]" to "@sashache"
)

val nameToNik = mapOf(
        "Alexander Podkhalyuzin" to "@alefas",
        "Aleksandr Gribovich" to "@oucouppnique",
        "Alexander Gorshenev" to "@alexander.gorshenev",
        "Alexander Prendota" to "@Alexander Prendota",
        "Alina Dolgikh" to "@alina.dolgikh",
        "Andrey Breslav" to "@abreslav",
        "Anton Bannykh" to "@anton.bannykh",
        "Alexey Sedunov" to "@alexey.sedunov",
        "Sergey Kuks" to "@qx",
        "Sergey Mashkov" to "@sergey.mashkov",
        "Denis Sharypov" to "@den.sharypov",
        "Denis Zharkov" to "@denis.zharkov",
        "Dmitry Petrov" to "@dmitry.petrov",
        "Dmitry Savvinov" to "@dmitry.savvinov",
        "Roman Elizarov" to "@elizarov",
        "Nikolay Krasko" to "@nk",
        "Sergey Igushkin" to "@sergey.igushkin",
        "Hadi Hariri" to "hhariri (@romanbelov)", // todo
        "Igor Chevdar" to "@igor.chevdar",
        "Ilmir Usmanov" to "@ilmir.usmanov",
        "Ilya Chernikov" to "@ilya.chernikov",
        "Ilya Gorbunov" to "@ilya.gorbunov",
        "Ilya Matveev" to "@ilya.matveev",
        "Konstantin Anisimov" to "@konstantin.anisimov",
        "Leonid Startsev" to "@Leonid Startsev",
        "Leonid Stashevsky" to "@leonid.stashevsky",
        "Lilia Abdulina" to "@lilia",
        "Maxim Shafirov" to "max (@stanislav.erokhin)", // todo
        "Michael Bogdanov" to "@max.kammerer",
        "Mikhail Glukhikh" to "@mikhailglukhikh",
        "Natalia Selezneva" to "@nastelaz",
        "Nicolay Mitropolsky" to "@nicolay.mitropolsky",
        "Nikolay Chashnikov" to "nik (@stanislav.erokhin)", // todo
        "Nikolay Igotti" to "@nikolay.igotti",
        "Ilya Ryzhenkov" to "@orangy",
        "Pavel Punegov" to "@Pavel Punegov",
        "Pavel Talanov" to "@pavel.talanov",
        "Roman Belov" to "@romanbelov",
        "Alexander Chernikov" to "@sashache",
        "Semyon Atamas" to "semyon.atamas (@romanbelov)", // todo
        "Sergey Bogolepov" to "@sergey.bogolepov",
        "Leonid Shalupov" to "shalupov (@yole)",
        "Simon Ogorodnik" to "@semoro",
        "Simon Scholz" to "@Simon Scholz",
        "Stanislav Erokhin" to "@stanislav.erokhin",
        "Svetlana Isakova" to "@svtk",
        "Svyatoslav Scherbina" to "@svyatoslav.scherbina",
        "Alexey Tsvetkov" to "@alexey.tsvetkov",
        "Alexander Udalov" to "@udalov",
        "Valentin Kipiatkov" to "@yole",
        "Vyacheslav Karpukhin" to "@vyacheslav.karpukhin",
        "Vasily Levchenko" to "@minamoto",
        "Viktoria Shirunova" to "@viktoria.shirunova",
        "Vyacheslav Gerasimov" to "@vyacheslav.gerasimov",
        "Yan Zhulanow" to "@yan",
        "Dmitry Jemerov" to "@yole",
        "Zalim Bashorov" to "@bashor",
        "Mikhail Zarechenskiy" to "@mikhail.zarechenskiy"
)
